apiVersion: argoproj.io/v1alpha1

kind: Application

metadata:
  name: loki # https://artifacthub.io/packages/helm/grafana/loki
  namespace: argo

spec:
  project: default

  source:
    path: ''
    repoURL: 'https://grafana.github.io/helm-charts'
    targetRevision: '6.15.0'
    chart: loki

    helm:
      #Notice: Helm way to pass parameters
      values: | #TODO
#        adminPassword: admin
#
#        datasources:
#          datasources.yaml:
#            apiVersion: 1
#            datasources:
#            - name: Prometheus
#              type: prometheus
#              url: http://prometheus-server
#              access: proxy
#              isDefault: true
#
#        dashboardProviders:
#          dashboardproviders.yaml:
#            apiVersion: 1
#            providers:
#              - name: 'default'
#                orgId: 1
#                folder: 'default'
#                type: file
#                disableDeletion: true
#                editable: true
#                options:
#                  path: /var/lib/grafana/dashboards/default

  destination:
    namespace: monitoring
    server: https://kubernetes.default.svc

  syncPolicy:
    automated:
      prune: false
      selfHeal: false