apiVersion: argoproj.io/v1alpha1

kind: Application

metadata:
  name: postgres
  namespace: argo

spec:
  project: default

  source:
    path: ''
    repoURL: 'https://charts.bitnami.com/bitnami/'
    targetRevision: '14'
    chart: postgresql
    helm:
      #Notice: ArgoCD way to pass parameters
      parameters:
        - name: primary.service.type
          value: 'ClusterIP'
        - name: primary.persistence.enabled
          value: 'false'
        - name: global.postgresql.auth.postgresPassword
          value: 'postgres'
        - name: global.postgresql.auth.database
          value: 'postgres'
      #Notice: Helm way to pass parameters
#      values: |
#        global:
#          postgresql:
#            auth:
#              postgresPassword: postgres
#              database: some-name
#        primary:
#          service:
#            type: ClusterIP
#          persistence:
#            enabled: false

  destination:
    namespace: database
    server: https://kubernetes.default.svc

  syncPolicy:
    automated:
      prune: false
      selfHeal: false