apiVersion: argoproj.io/v1alpha1

kind: Application

metadata:
  name: traefik # https://github.com/traefik/traefik-helm-chart/blob/master/traefik/values.yaml
  namespace: argo

spec:
  project: default

  source:
    path: ''
    repoURL: 'https://traefik.github.io/charts'
    targetRevision: '30.1.0'
    chart: 'traefik'
    helm:
      #Notice: ArgoCD way to pass parameters
      parameters:
        - name: service.type
          value: 'ClusterIP'
        - name: ingressRoute.dashboard.enabled
          value: 'true'

  destination:
    namespace: ingress
    server: https://kubernetes.default.svc

  syncPolicy:
    automated:
      prune: false
      selfHeal: false