apiVersion: argoproj.io/v1alpha1

kind: Application

metadata:
  name: cert-manager # https://artifacthub.io/packages/helm/grafana/loki
  namespace: argo

spec:
  project: default

  source:
    path: ''
    repoURL: 'https://charts.jetstack.io'
    targetRevision: 'cert-manager'
    chart: cert-manager

    helm:
      #Notice: Helm way to pass parameters
      values: |
        crds.enabled: true

  destination:
    namespace: default
    server: https://kubernetes.default.svc

  syncPolicy:
    automated:
      prune: false
      selfHeal: false