apiVersion: argoproj.io/v1alpha1

kind: Application

metadata:
  name: prometheus-pg-exporter # https://github.com/prometheus-community/helm-charts/blob/main/charts/prometheus/values.yaml
  namespace: argo

spec:
  project: default

  source:
    path: ''
    repoURL: 'https://prometheus-community.github.io/helm-charts'
    targetRevision: '6.3.0'
    chart: prometheus-postgres-exporter
#    helm:
#      #Notice: ArgoCD way to pass parameters
#      parameters:
#        - name:
#          value:
#        - name:
#          value:
#        - name:
#          value:

  destination:
    namespace: monitoring
    server: https://kubernetes.default.svc

  syncPolicy:
    automated:
      prune: false
      selfHeal: false