apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: argocd-application-controller-role
rules:
  - apiGroups: ["*"]
    resources: ["*"]
    verbs: ["create", "get", "list", "watch", "update", "patch", "delete"]
#  - apiGroups: ["admissionregistration.k8s.io"]
#    resources: ["validatingadmissionpolicybindings"]
#    verbs: ["get", "list", "watch"]
#  - apiGroups: ["vpcresources.k8s.aws"]
#    resources: ["cninodes"]
#    verbs: ["get", "list", "watch"]
#  - apiGroups: [""]
#    resources: ["serviceaccounts"]
#    verbs: ["get", "list", "watch"]
#  - apiGroups: [""]
#    resources: ["replicationcontrollers"]
#    verbs: ["get", "list", "watch"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: argocd-application-controller-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: argocd-application-controller-role
subjects:
  - kind: ServiceAccount
    name: argocd-application-controller
    namespace: argo
